[package]
name = "cyancia_view"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
cyancia_utils.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui_platform.workspace = true
log.workspace = true
thiserror.workspace = true
uuid.workspace = true
