[package]
name = "cyancia_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
downcast-rs.workspace = true
winit.workspace = true
iced_runtime.workspace = true
iced_core.workspace = true
iced_futures = { workspace = true, features = ["tokio"] }
iced_winit.workspace = true
iced_wgpu.workspace = true
wgpu.workspace = true
log.workspace = true
cyancia_utils.workspace = true
iced_graphics.workspace = true
rustc-hash.workspace = true
parking_lot.workspace = true
futures.workspace = true
tokio.workspace = true
