[package]
name = "cyancia_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
cyancia_runtime_derive.workspace = true
downcast-rs.workspace = true
winit.workspace = true
iced_runtime.workspace = true
iced_core.workspace = true
iced_futures.workspace = true
iced_winit.workspace = true
iced_wgpu.workspace = true
wgpu.workspace = true
log.workspace = true
cyancia_utils.workspace = true
iced_graphics.workspace = true
rustc-hash.workspace = true
parking_lot.workspace = true
futures.workspace = true
smol.workspace = true
parse-display.workspace = true
