[workspace]
members = [
    # "crates/cyancia_actions",
    # "crates/cyancia_app",
    "crates/cyancia_assets",
    # "crates/cyancia_canvas",
    # "crates/cyancia_graph",
    # "crates/cyancia_image",
    # "crates/cyancia_input",
    # "crates/cyancia_math",
    # "crates/cyancia_render",
    # "crates/cyancia_shader_graph",
    # "crates/cyancia_tools",
    "crates/cyancia_utils",
    "crates/cyancia_utils_derive",
    # "crates/cyancia_widgets",
    # "examples/*",
]
resolver = "2"

[workspace.dependencies]
# cyancia_graph = { version = "0.1.0", path = "crates/cyancia_graph" }
cyancia_utils = { version = "0.1.0", path = "crates/cyancia_utils" }
cyancia_utils_derive = { version = "0.1.0", path = "crates/cyancia_utils_derive" }
# cyancia_widgets = { version = "0.1.0", path = "crates/cyancia_widgets" }
# cyancia_input = { version = "0.1.0", path = "crates/cyancia_input" }
cyancia_assets = { version = "0.1.0", path = "crates/cyancia_assets" }
# cyancia_canvas = { version = "0.1.0", path = "crates/cyancia_canvas" }
# cyancia_tools = { version = "0.1.0", path = "crates/cyancia_tools" }
# cyancia_image = { version = "0.1.0", path = "crates/cyancia_image" }
# cyancia_render = { version = "0.1.0", path = "crates/cyancia_render" }
# cyancia_math = { version = "0.1.0", path = "crates/cyancia_math" }
# cyancia_actions = { version = "0.1.0", path = "crates/cyancia_actions" }
# cyancia_shader_graph = { version = "0.1.0", path = "crates/cyancia_shader_graph" }

iced = { version = "0.14", features = [
    "debug",
    "canvas",
    "selector",
], git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_beacon = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_core = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_debug = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_devtools = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_futures = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_graphics = { version = "0.14", features = [
    "geometry",
], git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_highlighter = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_program = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_renderer = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_runtime = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_selector = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_wgpu = { version = "0.14", features = [
    "geometry",
], git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_widget = { version = "0.14", features = [
    "wgpu",
], git = "https://github.com/443eb9/iced.git", branch = "0.14" }
iced_winit = { version = "0.14", git = "https://github.com/443eb9/iced.git", branch = "0.14" }
uuid = { version = "1", features = ["v4", "serde"] }
syn = "2"
quote = "1"
proc-macro2 = "1"
thiserror = "2"
num-traits = "0.2"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
serde = { version = "1", features = ["derive", "rc"] }
smallvec = "1"
toml = "0.9"
log = "0.4"
downcast-rs = "2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
indexmap = "2"
parking_lot = "0.12"
futures = "0.3"
bitflags = "2"
wgpu = "27"
glam = { version = "0.30", features = ["encase", "serde"] }
dashmap = "6"
wesl = { version = "0.3", features = ["package"] }
encase = "0.12"
bytemuck = "1"
image = "0.25"
palette = "0.7"
rayon = "1"
half = "2"
rfd = "0.16"
anyhow = "1"
dyn-clone = "1"
chrono = { version = "0.4", features = ["serde"] }
atomicow = "1"
tokio = { version = "1", default-features = false }
md5 = "0.8"
zip = "8"
parse-display = "0.10"
env_logger = "0.11"
path-clean = "1"
rusqlite = { version = "0.38", features = [
    "bundled-full",
] }

# [patch."https://github.com/443eb9/iced.git"]
# iced = { path = "D:/iced_fork", features = ["debug", "canvas"] }
# iced_beacon = { path = "D:/iced_fork/beacon" }
# iced_core = { path = "D:/iced_fork/core" }
# iced_debug = { path = "D:/iced_fork/debug" }
# iced_devtools = { path = "D:/iced_fork/devtools" }
# iced_futures = { path = "D:/iced_fork/futures" }
# iced_graphics = { path = "D:/iced_fork/graphics", features = ["geometry"] }
# iced_highlighter = { path = "D:/iced_fork/highlighter" }
# iced_program = { path = "D:/iced_fork/program" }
# iced_renderer = { path = "D:/iced_fork/renderer" }
# iced_runtime = { path = "D:/iced_fork/runtime" }
# iced_selector = { path = "D:/iced_fork/selector" }
# iced_wgpu = { path = "D:/iced_fork/wgpu", features = ["geometry"] }
# iced_widget = { path = "D:/iced_fork/widget", features = ["wgpu"] }
# iced_winit = { path = "D:/iced_fork/winit" }
