[workspace]
members = [
    "crates/cyancia_actions",
    "crates/cyancia_app",
    "crates/cyancia_assets",
    "crates/cyancia_brush",
    "crates/cyancia_bucket_tool",
    "crates/cyancia_canvas",
    "crates/cyancia_image",
    "crates/cyancia_math",
    "crates/cyancia_render",
    "crates/cyancia_selection_tool",
    "crates/cyancia_shader_graph",
    "crates/cyancia_shader_graph_derive",
    "crates/cyancia_theme",
    "crates/cyancia_tools",
    "crates/cyancia_undo",
    "crates/cyancia_utils",
    "crates/cyancia_utils_derive",
    "crates/cyancia_view",
    "crates/cyancia_widgets",
]
resolver = "3"
default-members = ["crates/cyancia_app"]

[workspace.package]
publish = false
edition = "2024"
rust-version = "1.96"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[workspace.dependencies]
cyancia_actions = { version = "0.1.0", path = "crates/cyancia_actions" }
cyancia_assets = { version = "0.1.0", path = "crates/cyancia_assets" }
cyancia_brush = { version = "0.1.0", path = "crates/cyancia_brush" }
cyancia_bucket_tool = { version = "0.1.0", path = "crates/cyancia_bucket_tool" }
cyancia_canvas = { version = "0.1.0", path = "crates/cyancia_canvas" }
cyancia_image = { version = "0.1.0", path = "crates/cyancia_image" }
cyancia_math = { version = "0.1.0", path = "crates/cyancia_math" }
cyancia_render = { version = "0.1.0", path = "crates/cyancia_render" }
cyancia_selection_tool = { version = "0.1.0", path = "crates/cyancia_selection_tool" }
cyancia_shader_graph = { version = "0.1.0", path = "crates/cyancia_shader_graph" }
cyancia_shader_graph_derive = { version = "0.1.0", path = "crates/cyancia_shader_graph_derive" }
cyancia_theme = { version = "0.1.0", path = "crates/cyancia_theme" }
cyancia_tools = { version = "0.1.0", path = "crates/cyancia_tools" }
cyancia_undo = { version = "0.1.0", path = "crates/cyancia_undo" }
cyancia_utils = { version = "0.1.0", path = "crates/cyancia_utils" }
cyancia_utils_derive = { version = "0.1.0", path = "crates/cyancia_utils_derive" }
cyancia_view = { version = "0.1.0", path = "crates/cyancia_view" }
cyancia_widgets = { version = "0.1.0", path = "crates/cyancia_widgets" }

anyhow = "1"
atomicow = "1"
bevy_color = "0.18"
bevy_math = { version = "0.18", git = "https://github.com/443eb9/bevy.git", branch = "release-0.18.1", features = [
    "serialize",
    "std",
    "curve",
    "encase",
] }
bitflags = "2"
bytemuck = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6"
downcast-rs = "2"
dyn-clone = "1"
encase = "0.12"
env_logger = "0.11"
fs_extra = "1"
futures = "0.3"
glam = { version = "0.30", features = ["encase", "serde", "bytemuck"] }
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "ccc1e7689203d09bfc88a0aae29473d1c289fa0c" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit"] }
half = "2"
image = "0.25"
indexmap = { version = "2", features = ["serde"] }
log = "0.4"
lyon = "1"
md5 = "0.8"
num-traits = "0.2"
palette = "0.7"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
parse-display = "0.11"
path-clean = "1"
proc-macro2 = "1"
quote = "1"
rayon = "1"
rfd = "0.17"
ringbuffer = "0.16"
rusqlite = { version = "0.40", features = ["bundled-full"] }
rustc-hash = "1"
schemars = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
smallvec = "1"
smol = "2"
syn = "2"
thiserror = "2"
toml = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }
variadics_please = "2"
wesl = { version = "0.4", features = ["package", "naga-ext"] }
wgpu = "29"
winit = "0.30"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
zip = "8"
