[package]
name = "cyancia_selection_tool"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy_math.workspace = true
bytemuck.workspace = true
cyancia_bucket_tool.workspace = true
cyancia_canvas.workspace = true
cyancia_image.workspace = true
cyancia_render.workspace = true
cyancia_tools.workspace = true
cyancia_utils.workspace = true
encase.workspace = true
glam.workspace = true
gpui.workspace = true
gpui-component.workspace = true
indexmap.workspace = true
lyon.workspace = true
tracing.workspace = true
wesl.workspace = true
wgpu.workspace = true

[build-dependencies]
cyancia_image.workspace = true
wesl.workspace = true

[lints]
workspace = true
