[package]
name = "cyancia_transform_tool"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bevy_math.workspace = true
bitflags.workspace = true
cyancia_canvas.workspace = true
cyancia_math.workspace = true
cyancia_image.workspace = true
cyancia_input.workspace = true
cyancia_render.workspace = true
cyancia_tools.workspace = true
cyancia_runtime.workspace = true
cyancia_undo.workspace = true
cyancia_utils.workspace = true
cyancia_widgets.workspace = true
encase.workspace = true
glam.workspace = true
tracing.workspace = true
iced_aw.workspace = true
iced_core.workspace = true
iced_graphics.workspace = true
iced_wgpu.workspace = true
iced_widget.workspace = true
iced_runtime.workspace = true
wgpu.workspace = true
