[package]
name = "cyancia_undo"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
cyancia_utils.workspace = true
downcast-rs.workspace = true
futures.workspace = true
tracing.workspace = true
gpui.workspace = true
uuid.workspace = true

[lints]
workspace = true
