[package]
name = "cyancia_shader_graph"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid.workspace = true
cyancia_utils.workspace = true
iced_core.workspace = true
iced_wgpu.workspace = true
log.workspace = true
thiserror.workspace = true
iced_widget.workspace = true
iced_graphics.workspace = true
cyancia_widgets.workspace = true
anyhow.workspace = true
serde.workspace = true
dyn-clone.workspace = true
indexmap.workspace = true
toml.workspace = true
downcast-rs.workspace = true
glam.workspace = true
parking_lot.workspace = true
