[package]
name = "cyancia_actions"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
cyancia_assets.workspace = true
cyancia_bucket_tool.workspace = true
cyancia_canvas.workspace = true
cyancia_image.workspace = true
cyancia_render.workspace = true
cyancia_tools.workspace = true
cyancia_undo.workspace = true
cyancia_utils.workspace = true
cyancia_view.workspace = true
futures.workspace = true
glam.workspace = true
gpui.workspace = true
image.workspace = true
log.workspace = true
parking_lot.workspace = true
parse-display.workspace = true
rfd.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
uuid.workspace = true
