[package]
name = "cyancia_render"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
cyancia_utils.workspace = true
wesl.workspace = true
encase.workspace = true
iced_wgpu.workspace = true
iced_widget.workspace = true
cyancia_runtime.workspace = true
futures.workspace = true
iced_renderer.workspace = true
serde.workspace = true
parse-display.workspace = true
anyhow.workspace = true
bevy_math.workspace = true
image.workspace = true
cyancia_assets.workspace = true
zip.workspace = true
thiserror.workspace = true
toml.workspace = true
bytemuck.workspace = true

[build-dependencies]
wesl.workspace = true
