[package]
name = "cyancia_utils"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bevy_color.workspace = true
cyancia_utils_derive.workspace = true
downcast-rs.workspace = true
dyn-clone.workspace = true
gpui.workspace = true
gpui-component.workspace = true
tracing.workspace = true
