[package]
name = "cyancia_color_selector"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
bytemuck.workspace = true
cyancia_color.workspace = true
cyancia_render.workspace = true
cyancia_widgets.workspace = true
encase.workspace = true
parse-display.workspace = true
glam.workspace = true
gpui.workspace = true
gpui-component.workspace = true
moxcms.workspace = true
wesl.workspace = true
wgpu.workspace = true

[lints]
workspace = true
