[package]
name = "cyancia_color"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
cyancia_utils.workspace = true
gpui.workspace = true
moxcms.workspace = true
parse-display.workspace = true

[lints]
workspace = true
