[package]
name = "cyancia_image"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bevy_math.workspace = true
bytemuck.workspace = true
cyancia_render.workspace = true
cyancia_shader_graph.workspace = true
cyancia_utils.workspace = true
cyancia_widgets.workspace = true
dashmap.workspace = true
dyn-clone.workspace = true
encase.workspace = true
glam.workspace = true
gpui.workspace = true
gpui-component.workspace = true
half.workspace = true
image.workspace = true
indexmap.workspace = true
log.workspace = true
palette.workspace = true
parking_lot.workspace = true
parse-display.workspace = true
rayon.workspace = true
serde.workspace = true
uuid.workspace = true
wesl.workspace = true
wgpu.workspace = true

[build-dependencies]
wesl.workspace = true
