[package]
name = "cyancia_canvas"
version = "0.1.0"
edition = "2024"

[dependencies]
cyancia_assets.workspace = true
log.workspace = true
parking_lot.workspace = true
cyancia_utils.workspace = true
wgpu.workspace = true
glam.workspace = true
cyancia_image.workspace = true
cyancia_render.workspace = true
encase.workspace = true
cyancia_math.workspace = true
bytemuck.workspace = true
uuid.workspace = true
serde.workspace = true
bevy_math.workspace = true
cyancia_tools.workspace = true
parse-display.workspace = true
gpui.workspace = true
image.workspace = true
gpui-component.workspace = true
futures.workspace = true

[build-dependencies]
wesl.workspace = true
cyancia_render.workspace = true
cyancia_image.workspace = true
