[package]
name = "cyancia_app"
version = "0.1.0"
edition = "2024"

[dependencies]
cyancia_canvas.workspace = true
log.workspace = true
cyancia_assets.workspace = true
futures.workspace = true
tracing-subscriber.workspace = true
parking_lot.workspace = true
rfd.workspace = true
cyancia_image.workspace = true
image.workspace = true
glam.workspace = true
cyancia_tools.workspace = true
uuid.workspace = true
cyancia_actions.workspace = true
wgpu.workspace = true
cyancia_render.workspace = true
cyancia_brush.workspace = true
cyancia_shader_graph.workspace = true
bevy_math.workspace = true
cyancia_widgets.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
thiserror.workspace = true
cyancia_theme.workspace = true
cyancia_view.workspace = true
anyhow.workspace = true

[build-dependencies]
fs_extra.workspace = true
