[package]
name = "cyancia_widgets"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bevy_math.workspace = true
cyancia_math.workspace = true
glam.workspace = true
gpui.workspace = true
gpui-component.workspace = true
num-traits.workspace = true
refineable = { git = "https://github.com/zed-industries/zed" }
